apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaimage-deploy
  labels:
   app: myjavaimage
spec:   
   replicas: 3
   selector:
      matchLabels:
          app: myjavaimage
   template:
     metadata:
       labels:
        app: myjavaimage
     spec:
      containers:
      - name: myjavaimage-container
        image: shanu0002/myjavaimage04june22:1
        ports:
        - containerPort: 8080
